version: '3.8'

services:
  db:
    image: mariadb:10.8.3
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    volumes:
      - db-data:/var/lib/mysql
    profiles: [ "develop", "production" ]

  web-prod:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: sh -c "cd src/filmdb && gunicorn filmdb.wsgi:application --bind web-prod:80"
    depends_on:
      db:
        condition: service_started
    profiles: [ "production" ]

  nginx:
    build: ./docker/nginx
    ports:
      - 8000:8000
    volumes:
      - staticfiles:/app/static
      - mediafiles:/app/media
    links:
      - "web-prod:web-prod"
    depends_on:
      web-prod:
        condition: service_started
    profiles: [ "production" ]

  web-dev:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    command: >
      python bin/manage.py runserver 0.0.0.0:8090
    ports:
      - 8090:8090
    volumes:
      - staticfiles:/app/static
      - mediafiles:/app/media
    depends_on:
      db:
        condition: service_started
    profiles: [ "develop" ]

volumes:
  db-data:
  staticfiles:
  mediafiles:
